GET http://localhost:8001/appUsers?username=zemtsov_a22

###

POST http://localhost:8001/appUsers
Content-Type: application/json

{
  "username": "zemtsov_a22",
  "password": "asdasdasdsad222",
  "enabled": null,
  "roles": [
    {
      "id": 1,
      "nameToSystem": "ROLE_EMPLOYEE",
      "namesToView": {
        "en": "Employee",
        "ru_RU": "Соискатель"
      },
      "namesToDescription": {
        "en": "Provides the ability to work with resume.",
        "ru_RU": "Предоставляет возможность работы с резюме."
      },
      "nameToView": "Соискатель",
      "nameToDescription": "Предоставляет возможность работы с резюме."
    }
  ],
  "profile": {
    "lastName": "Земцов",
    "firstName": "Алексей",
    "middleName": "Владимирович",
    "genderId": 1,
    "numberPhone": {
      "code": "+7",
      "number": "9530190297",
      "fullNumber": "+79530190297"
    },
    "email": "test@mail.ru",
    "dateBirthday": "1997-11-20",
    "avatarId": null,
    "fullName": "Земцов Алексей Владимирович",
    "age": null
  }
}

###