GET http://localhost:8002/articles?campaignStatusId=4&caption=Заголовок

###

GET http://localhost:8002/articles/4

###

POST http://localhost:8002/articles
Content-Type: application/json

{
  "caption": "Заголовок",
  "description": "Описание",
  "text": "Основной текст",
  "campaign": {
    "campaignStatus": {
      "id": 1
    }
  },
  "articleType": {
    "id": 1
  }
}

###

PUT http://localhost:8002/articles/4
Content-Type: application/json

{
  "id" : "4",
  "caption": "Заголовок",
  "description" : "Описание",
  "text" : "Основной текст",
  "campaign" : {
    "id" : "15",
    "campaignStatus": { "id": 2 }
  },
  "articleType": {
    "id": 1
  }
}

###

DELETE http://localhost:8002/articles/4

###