GET http://localhost:8002/campaigns

###

GET http://localhost:8002/campaigns/9

###

POST http://localhost:8002/campaigns
Content-Type: application/json

{
  "dateCreate": "2020-06-03T12:00:00",
  "dateStart": "2020-06-03T12:00:00",
  "dateFinish": "2020-06-22T12:00:00",
  "campaignStatus": { "id": 4 }
}

###

PUT http://localhost:8002/campaigns/9
Content-Type: application/json

{
  "id": 9,
  "campaignStatus": { "id": 1 }
}

###

DELETE http://localhost:8002/campaigns/4

###